name: Releases

on:
  push:
    tags:
      # These aren't regexps. They are "Workflow Filter patterns"
      - v[0-9]+.[0-9]+.[0-9]
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+

jobs:
  build-release:
    strategy:
      fail-fast: false
      matrix:
        runners:
          - ubuntu-latest
#          - macos-latest
#          - macOS-arm64
#          - windows-2019
    runs-on: ${{ matrix.runners }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install-dependencies
        name: install dependencies
      - name: set version
        shell: bash
        run: echo "TELEPRESENCE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - run: make release-binary
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: build-output/release
          retention-days: 1
#      - if: runner.os == 'Linux' && runner.arch == 'X64'
#        name: Upload Docker image
#        run: |
#          docker login -u="${{ secrets.DOCKERHUB_USERNAME }}" -p="${{ secrets.DOCKERHUB_PASSWORD }}"
#          make push-tel2-image

  release:
    runs-on: ubuntu-latest
    needs: build-release
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Determine if version is valid semver
        id: semver_check
        run: |
          if [[ "${{ github.ref_name }}" =~ ^v[0-9]+.[0-9]+.[0-9]$ ]]; then
          echo "MAKE_LATEST=true" >> $GITHUB_ENV
          else
          echo "MAKE_LATEST=false" >> $GITHUB_ENV
          fi
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "binaries/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: ${{ env.MAKE_LATEST }}
          body: |
            ## Official Release Artifactss
            ### Linux
               - 📦 [telepresence-linux-amd64](https://app.getambassador.io/download/tel2oss/releases/download/${{ github.ref_name }}/telepresence-linux-amd64)
            For more builds across platforms and architectures, see the `Assets` section below.
            And for more information, visit our [installation docs](https://www.telepresence.io/docs/latest/quick-start/).

